name: "Test"
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: jjmerelo/raku-test:latest
      options: --user root
    steps:
      - name: Create dirs
        run:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: su - raku  && zef install --deps-only .
      - name: Test
        run: su - raku && zef --debug test .


